alias: Alles uit wanneer we van huis gaan
description: ""
triggers:
  - entity_id:
      - zone.home
    to: "0"
    trigger: state
conditions: []
actions:
  - data: {}
    target:
      entity_id: light.all_lights
    action: light.turn_off
  - data: {}
    target:
      device_id:
        - bf95a24944350c43f307e08e4b4ed465
        - 12c27fd464189ea8a982c7f6717bc78f
        - 2fd804bee45e4ee55a7edc637f347eba
    action: media_player.media_stop
mode: single
