alias: Lampen woonkamer aan/uit
description: ""
triggers:
  - event: sunset
    offset: "- 00:20:00"
    id: Zon gaat onder
    trigger: sun
  - entity_id:
      - zone.home
    from: "0"
    id: Thuiskomen
    trigger: state
conditions: []
actions:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - Zon gaat onder
          - condition: numeric_state
            entity_id: zone.home
            above: 0
        sequence:
          - target:
              device_id:
                - 999ffc9b7c11eaa884b98454bdb9b248
                - 76e044d807f549f31c91d9a37ee294eb
                - 4253b06aa7efdb084156487f007089d2
            data: {}
            action: light.turn_on
      - conditions:
          - condition: trigger
            id:
              - Thuiskomen
          - condition: state
            entity_id: sun.sun
            state: below_horizon
            for:
              hours: 0
              minutes: 0
              seconds: 0
          - condition: time
            before: "23:00:00"
        sequence:
          - target:
              device_id:
                - 999ffc9b7c11eaa884b98454bdb9b248
                - 76e044d807f549f31c91d9a37ee294eb
                - 4253b06aa7efdb084156487f007089d2
            data: {}
            action: light.turn_on
mode: single
