alias: Motion Toilet
description: ""
trigger:
  - type: motion
    platform: device
    device_id: 1ea2a8c8c9fdd268dc17096b18c8e2ac
    entity_id: 270d1ce26ddf06b2ec5d3af611eefaf7
    domain: binary_sensor
    id: Detected motion
  - type: no_motion
    platform: device
    device_id: 1ea2a8c8c9fdd268dc17096b18c8e2ac
    entity_id: 270d1ce26ddf06b2ec5d3af611eefaf7
    domain: binary_sensor
    id: Motion stopped
    for:
      hours: 0
      minutes: 1
      seconds: 20
condition: []
action:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - Detected motion
          - condition: time
            after: "07:00:00"
            before: "00:00:00"
            weekday:
              - mon
              - tue
              - wed
              - thu
              - fri
        sequence:
          - type: turn_on
            device_id: 797f2c83cc6345b05e59703ce900b0e4
            entity_id: 783d053b964fdd8e0231e17d186ebac3
            domain: light
            brightness_pct: 70
      - conditions:
          - condition: trigger
            id:
              - Motion stopped
        sequence:
          - service: light.turn_off
            data: {}
            target:
              device_id: 797f2c83cc6345b05e59703ce900b0e4
      - conditions:
          - condition: trigger
            id:
              - Detected motion
          - condition: time
            after: "08:30:00"
            before: "01:00:00"
            weekday:
              - sat
              - sun
        sequence:
          - type: turn_on
            device_id: 797f2c83cc6345b05e59703ce900b0e4
            entity_id: 783d053b964fdd8e0231e17d186ebac3
            domain: light
            brightness_pct: 70
mode: single
