alias: Reistijd naar huis Fleur
description: ""
trigger:
  - platform: zone
    entity_id: person.fleur
    zone: zone.werk_fleur
    event: leave
condition:
  - condition: time
    after: "16:00:00"
    weekday:
      - mon
      - tue
      - wed
      - thu
action:
  - service: homeassistant.update_entity
    data: {}
    target:
      entity_id: automation.verlaten_van_werk
  - service: notify.mobile_app_sm_g998b
    data:
      message: >-
        Ze is rond {{now().strftime("%H:%M")}} vertrokken en ongeveer over
        {{states('sensor.waze_reistijd_werk_fleur')}} minuten thuis.
mode: single
