alias: Reset boolean weer info
description: ""
trigger:
  - platform: time
    at: "06:00:00"
condition: []
action:
  - service: input_boolean.turn_on
    target:
      entity_id: input_boolean.weer_info_ochtend
    data: {}
mode: single
