alias: Vakantie modus
description: D.m.v. input_boolean
trigger:
  - platform: state
    entity_id:
      - input_boolean.vakantiemodus
    to: "on"
    alias: Op vakantie
    id: Op vakantie
  - platform: state
    entity_id:
      - input_boolean.vakantiemodus
    to: "off"
    alias: Terug van vakantie
    id: Terug van vakantie
condition: []
action:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - Op vakantie
        sequence:
          - service: switch.turn_off
            target:
              area_id:
                - woonkamer
                - slaapkamer
            data: {}
          - service: media_player.media_stop
            target:
              device_id:
                - bf95a24944350c43f307e08e4b4ed465
                - 12c27fd464189ea8a982c7f6717bc78f
            data: {}
          - service: light.turn_off
            target:
              area_id:
                - hal
                - slaapkamer
                - woonkamer
            data: {}
mode: single
